; /etc/supervisor/conf.d/dbwe.conf
; Startet Gunicorn automatisch und startet ihn bei Absturz neu (Kap. 13.3.7)
[program:dbwe]
command=/home/student/dbwe/venv/bin/gunicorn -b localhost:8000 -w 4 dbwe:app
directory=/home/student/dbwe
user=student
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
